// File generated by FlutterFire CLI.
// This is a placeholder - you need to run:
// flutterfire configure
// to generate the actual Firebase configuration

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'your-web-api-key-placeholder',
    appId: 'your-web-app-id-placeholder',
    messagingSenderId: 'your-sender-id-placeholder',
    projectId: 'your-project-id-placeholder',
    authDomain: 'your-project-id.firebaseapp.com',
    storageBucket: 'your-project-id.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'your-android-api-key-placeholder',
    appId: 'your-android-app-id-placeholder',
    messagingSenderId: 'your-sender-id-placeholder',
    projectId: 'your-project-id-placeholder',
    storageBucket: 'your-project-id.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'your-ios-api-key-placeholder',
    appId: 'your-ios-app-id-placeholder',
    messagingSenderId: 'your-sender-id-placeholder',
    projectId: 'your-project-id-placeholder',
    storageBucket: 'your-project-id.appspot.com',
    iosBundleId: 'com.example.resumeAtsMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'your-ios-api-key-placeholder',
    appId: 'your-ios-app-id-placeholder',
    messagingSenderId: 'your-sender-id-placeholder',
    projectId: 'your-project-id-placeholder',
    storageBucket: 'your-project-id.appspot.com',
    iosBundleId: 'com.example.resumeAtsMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'your-web-api-key-placeholder',
    appId: 'your-web-app-id-placeholder',
    messagingSenderId: 'your-sender-id-placeholder',
    projectId: 'your-project-id-placeholder',
    authDomain: 'your-project-id.firebaseapp.com',
    storageBucket: 'your-project-id.appspot.com',
  );
}
